name: Deploy Production Application to Server

on:
  push:
    branches: [production]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.PRODUCTION_PORT }}
          script: |
            cd ${{ secrets.PRODUCTION_PATH }}

            echo "--> Setup NVM..."
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh

            nvm install 22.16.0
            nvm use 22.16.0

            echo "--> Stop application..."
            npm run pm2:stop

            echo "--> Git sync..."
            git fetch origin
            git checkout production
            git pull origin production
            
            echo "--> Clear build cache..."
            rm -rf node_modules/.bin/next
            rm -rf .next

            echo "--> Install dependencies..."
            npm ci

            echo "--> Build application..."
            npm run build

            echo "--> Set permission..."
            sudo chown -R www:www . && sudo find . \( -type d -exec chmod 755 {} \; \) -o \( -type f -exec chmod 644 {} \; \) && sudo chmod -R 775 .next node_modules public

            echo "--> Run application..."
            npm run pm2:restart || npm run pm2:start
            pm2 startup
            pm2 save
